### ISSUE TITLE
@aws-crypto/client-node module version is wrong!

### ISSUE THREAD

**Issue by lahuman** [aws/aws-encryption-sdk-javascript#1031]
### Problem:

I tried using @aws-crypto/client-node module. But I got some error. 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/6156679/194507367-5151f4bc-df4f-4c4c-bf79-283e7397c311.png">

Because The module version is ```1.9.1```.

![image](https://user-images.githubusercontent.com/6156679/194507139-69ce16df-b80b-4429-8c3b-848820650af8.png)

After I tried using ```3.1.1 ```. 

Then I got encode / decode data.

**Comment by josecorella** [comment]
Hello @lahuman,

Thank you for cutting an issue, you got the error because you are using version 1.x of the @aws-crypto/client-node module. Major version 1.x has reached end of support and only supports commitment policy FORBID_ENCRYPT_ALLOW_DECRYPT . We have more detailed information regarding commitment policies in our [docs](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/migration-guide.html#migrate-stage1).

Please reopen the issue if you have further questions.
