### ISSUE TITLE
`KmsKeyringNode` constructor in deadlock in Lambda running on top of NodeJS 18

### ISSUE THREAD

**Issue by DomDerrien** [aws/aws-encryption-sdk-javascript#1103]
# Issue description
- The code below is registered as a custom email sender with Cognito
- The code is correctly executed when the lambda is set with the runtime value `Runtime.NODEJS_16_X` in our CDK construct.
- With the runtime set with `Runtime.NODEJS_18_X`, the code is always killed b/c it reaches its timeout limit. The deadlock source is the constructor of `KmsKeyringNode`.

```json
"node_modules/@aws-crypto/kms-keyring": {
    "version": "3.2.0",
    "resolved": "https://registry.npmjs.org/@aws-crypto/kms-keyring/-/kms-keyring-3.2.0.tgz",
    "integrity": "sha512-eFCJTas7VjYaIOEj7urLsj1fDzFTlenwxB7AbGvYNfrOqLwLg6OGO/dSsyE3f14yph1DqmCsBU9OVj2f4t8Nog==",
    "dependencies": {
        "@aws-crypto/material-management": "^3.2.0",
        "tslib": "^2.2.0"
    }
},
```

# Sources
- https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/js-examples.html

# Code snippet
```TypeScript
import { Callback, Context, CustomEmailSenderTriggerEvent } from 'aws-lambda';
import { toByteArray } from 'base64-js';
import { CommitmentPolicy } from '@aws-crypto/material-management-node';
import { buildDecrypt } from '@aws-crypto/decrypt-node';
import { KmsKeyringNode } from '@aws-crypto/kms-keyring-node';

const encryptionKeyId = process.env.USER_POOL_TRIGGER_KEY_ID as string; // <-- env var set by the construct at setup time
const userPoolTriggerKeyring = new KmsKeyringNode({ keyIds: [encryptionKeyId] }); // <-- deadlock source
const { decrypt } = buildDecrypt(CommitmentPolicy.REQUIRE_ENCRYPT_ALLOW_DECRYPT);

export async function handler(event: CustomEmailSenderTriggerEvent, context: Context, callback: Callback) { ... }
```

**Comment by DomDerrien** [comment]
Hi @lucasmcdonald3,

My infrastructure is deployed with the CDK. On Monday, I upgraded 10 lambdas runtime values from `NODEJS_16_X` to `NODEJS_18_X`. I also refreshed all dependencies (`npm update`) before updating my stack. Everything went smoothly except for the lambda setup in Cognito to send emails.

This broken lambda implements a function that extracts an encrypted code used for email account confirmation, password reset, etc. The code is set as illustrated in the code snippet from above and works flawlessly when run on top of Node 16. The lambda control never comes back when run on top of Node 18.

Here are the answers to your questions:
- The CloudWatch log mentions the Node version: `16.v12` for the working setup and `18.v5` for the killed processes.
- There's no log or anything because the process is killed before the process output is even transferred to CloudWatch. It's like the constructor induces an infinite loop, giving no chance to Node to process any other events.
- By simply disabling more and more code parts, by redeploying, and by testing again a request to Cognito. When I identified the `KmsKeyringNode` constructor as the culprit, I tried to go back to version `3.1.0`, and without progress, I reverted back to Node 16... A very tedious process ;)
- My timeout value was 10 minutes (as you can see below). I changed it to 1 minute. On Node 16 with a cold start, the process can consume up to 4-5 seconds.
- None of my other lambdas use the `@aws-crypto` library and work as expected on Node 18.
- Yes, the encrypted key id is set as an environment parameter with the help of the CDK (see the last screenshot). The same code works with Node 16...

Last point:
- It's not related to Cognito b/c I reproduced the deadlock from the Lambda page in the AWS console, with the `Test` page and a payload successfully processed.

-----

<img width="1025" alt="Screenshot 2023-03-09 at 6 35 29 PM" src="https://user-images.githubusercontent.com/43402/224184598-b2990351-0fcc-4fb4-aaa1-dcc0cc5c9eab.png">

<img width="1028" alt="Screenshot 2023-03-09 at 6 39 05 PM" src="https://user-images.githubusercontent.com/43402/224185051-7aa19ed1-c499-4262-97e7-e082ee198d8e.png">

<img width="724" alt="Screenshot 2023-03-09 at 6 59 54 PM" src="https://user-images.githubusercontent.com/43402/224188349-b0dc89d7-be7a-44b0-bf71-8b2e8db35d29.png">

**Comment by lucasmcdonald3** [comment]
Hi @DomDerrien,

Thanks for the extra information. I think I was able to reproduce the same issue you were seeing.

To reproduce this, I deployed a Lambda via CDK.
The Lambda function’s code would `require("@aws-crypto/kms-keyring-node")`, then log success.
This Lambda would succeed on Node 16 but time out on Node 18.
(I suspect you see a timeout when calling the `KmsKeyringNode` constructor because this is the first call you make to the library.
Your `import` happens asynchronously, but calling the library would block execution until the import completes.)

The root cause appears to be that the Node 18 Lambda runtime environment you’re using doesn’t automatically include the AWS SDK for JavaScript V2, which this package depends on.
The SDK V2 has a size of ~80 MB unzipped.
AWS Lambda bundles AWS SDK libraries with specific runtimes, which cuts down on deployment package size.
From this [page](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), the the Node 18 runtime environment you’re using is bundled with the SDK V3, but not the SDK V2.
This package’s usage of SDK V3 is ~5MB, since it only depends on its KMS-related modules. However, the SDK V2 is not modular, so this package must depend on the entire ~80MB package.

I used CDK to bundle a Node 18 runtime with this package, which resulted in a bundled deployment size of ~32MB.
(Swapping this to Node 16 resulted in a bundled deployment size of ~8kB: much smaller, since the Node 16 runtime environment includes SDK V2).
I suspect your Lambda function doesn’t have enough memory allocated to unzip the larger file the CDK deploys, and the code times out.

We plan to deprecate this package’s usage of AWS SDK for JavaScript V2 in the future.
I would expect that this would decrease Node 18 CDK deployment file sizes, since CDK wouldn’t need to bundle the SDK V2 with your deployment.

In the meantime, I have a handful of suggestions for how to work around this:
1. Increase Lambda memory configuration. From your CDK code, it looks like your Lambda is using the default memory configuration of 128 MB. My local Lambda that had been timing out with 128 MB of configured memory succeeded after upping this to 256 MB (but probably needs ~512 MB to run safely.) This is the easiest workaround I can think of, and I can confirm this fixed the issue on my end.
2. Create a [custom Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) that bundles Node 18 with the AWS SDK for JavaScript V2. I’d expect that offloading the SDK V2 to the runtime would cut down on the deployment filesize. I haven’t tested this, but this also seems like a fruitful approach.

Let me know if either of these work for you, or if I can clarify any of the above.

**Comment by DomDerrien** [comment]
Hey @lucasmcdonald3,

I think you nailed down the root cause!

My update from Node 16 to Node 18 is driven by the wish to stop packaging the AWS SDK v3 with the app—I've been using V3 for a long time, having to ship it every time. I'm about to update the `NodeJSFunction` declaration with:
```TypeScript
        const cognitoPreSignUpTriggerFn = new NodejsFunction(this, 'CognitoPreSignUpTriggerFn-', {
            bundling: {
               // ...
                externalModules: [
                    // AWS SDK v3
                    '@aws-sdk/client-cognito-identity-provider',
                    '@aws-sdk/client-dynamodb',
                    '@aws-sdk/client-kms',
                    '@aws-sdk/client-lambda',
                    '@aws-sdk/client-s3',
                    '@aws-sdk/client-ssm',
                    '@aws-sdk/util-dynamodb',
                    // AWS Powertools, from a layer
                    '@aws-lambda-powertools/commons',
                    '@aws-lambda-powertools/logger',
                    '@aws-lambda-powertools/metrics',
                    '@aws-lambda-powertools/tracer',
                ],
                // ...
           });
```

I should have thought about the dependency on the AWS SDK V2! I read that `externalModules` has the default value: [\['aws-sdk'\]](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda-nodejs.BundlingOptions.html#externalmodules).

As the lambda is just called from Cognito to send customized emails (to send a code to verify email addresses, to send a code for password reset requests, etc.), it's barely called. So I'm going to leave it packaged for Node 16, relying on the SDK V2. I'll refactor the code a bit later.

Other lambdas are working now on Node 18 with reduced package sizes. I have not yet measured the performance improvement but I guess it goes in the right direction: smaller packages, and fewer dependencies.

Thanks for your help.

**Comment by DomDerrien** [comment]
This ticket can be closed b/c the issue is not related to the library, only to the Lambda environment. Node 16 provides an environment with the AWS SDK V2 installed while Node 18 provides an environment with the AWS SDK v3. The library I was using was relying on the V2 that I forgot to package with the deployed code. Oups.
