### ISSUE TITLE
No clear way to decrypt AWS RDS Aurora Activity Streams data

### ISSUE THREAD

**Issue by safakadir** [aws/aws-encryption-sdk-javascript#1194]
### Problem:

There is no documentation, or examples, or a straight forward way to come up with to decrypt the AWS RDS Aurora Activity Streams data using available javascript libraries. All I could find is that decrypt methods require keyring objects. But it's not clear or known by developers how to create correct keyring to decrypt the AWS RDS Aurora Activity Streams data.

### More details: 

The AWS RDS Aurora Activity Streams data has two significant encrypted fields: `databaseActivityEvents` and `dataKey`. The decryption process described in [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/DBActivityStreams.Monitoring.html) as follows:

> Take the following steps to decrypt the contents of the databaseActivityEvents field:
> 1. Decrypt the value in the key JSON field using the KMS key you provided when starting database activity stream. Doing so returns the data encryption key in clear text.
> 2. Base64-decode the value in the databaseActivityEvents JSON field to obtain the ciphertext, in binary format, of the audit payload.
> 3. Decrypt the binary ciphertext with the data encryption key that you decoded in the first step.
> 4. Decompress the decrypted payload.

I've done first 2 steps, but step 3 is unclear for javascript sdk. `databaseActivityEvents` follows the format described [here](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/message-format.html).

More details in this [stackoverflow post](https://stackoverflow.com/questions/76850792/decrypt-aws-rds-aurora-activty-stream-in-javascript-nodejs)

### Solution:

Please provide an easy way and its documentation to decrypt the message when there is a customer managed KMS key, an encrypted message, and an encrypted data key.

**Comment by justplaz** [comment]
Hey, thanks for reaching out. 

First, it appears that the implementation of RDS Aurora Activity Streams is to use KMS to encrypt a raw AES key used as a `JceMasterKey` in the AWS Encryption SDK. Though AWS KMS is involved, this approach is not compatible with the `KMSMasterKey` or KMS keyrings included in the AWS ESDK (which automatically handles making requests to KMS and manages its own encryption context).  

Second, since you are using Javascript to decrypt, you have to "convert" to using keyrings instead of master keys/key providers. This means that you have to use the `RawAesKeyring` with the "manually" decrypted key material instead of the Java equivalent (`JceMasterKey`). 

Finally, it looks like the issue with the code snippet in the StackOverflow post is with the key name/namespace. Per the example, the provider ID and key ID are "BC" and "DataKey", and [these terms translate to](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/master-key-provider-interface.md#terms) key namespace and key name when used with a keyring. If you use those values instead, the decryption should succeed.

**Comment by safakadir** [comment]
Thank you very much @justplaz! It's successfully decrypting right now. Without your help, I couldn't find correct values to provide as keyname and keyspace.

I'm sharing working code snippet for those having similar problems:
```
export async function decryptRawAesKeyring(encryptedDataBase64: string, decryptedKey: Uint8Array) {
  const { decrypt } = buildClient(CommitmentPolicy.FORBID_ENCRYPT_ALLOW_DECRYPT)
  const wrappingSuite = RawAesWrappingSuiteIdentifier.AES256_GCM_IV12_TAG16_NO_PADDING
  const keyring = new RawAesKeyringNode({
    keyName: "DataKey",
    keyNamespace: "BC",
    wrappingSuite,
    unencryptedMasterKey: key
  })
  const { messageHeader, plaintext } = await decrypt(keyring, Buffer.from(encDataBase64, 'base64'))
  return { messageHeader, plaintext }
}
```
The plaintext should also be decompressed afterwards:
`const content = JSON.parse(zlib.gunzipSync(result.plaintext).toString())`

**Comment by safakadir** [comment]
@zemacnica
Node version: v16.17.1 
@aws-crypto/client-node version: 4.0.0
