### ISSUE TITLE
@aws-crypto/client-browser no exported member 'encrypt' or 'decrypt'.

### ISSUE THREAD

**Issue by vesnathan** [aws/aws-encryption-sdk-javascript#1210]
### Problem:

Trying to use this library as per all the documentation I can find online. They say to use methods encrypt and decrypt, but they don't seem to exist...

**Comment by lavaleri** [comment]
Hi @vesnathan. If you are seeing a `no exported member 'encrypt' or 'decrypt'.` error, you are likely trying to import these methods instead of building a client, as shown here: https://github.com/aws/aws-encryption-sdk-javascript/blob/master/modules/example-browser/src/kms_simple.ts#L25-L27

As of version 2.0.0 of our library, that is the correct way to get `encrypt` and `decrypt`.

Let us know if this resolves your issue.
