### ISSUE TITLE
Wrap UTF8 encoding/decoding errors

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-javascript#25]
All UTF8 encoding/decoding failures should be normalized to our external-facing errors.

**Comment by seebees** [comment]
As it turns out, most JS decoding replaces invalid utf8 bytes
with the unicode replacement characters.
I'm going to leave this open for now as a know issue
that invalid utf8 values will simply be returns as strings.

This is primarily an issue for encryption context
and keyring names and namespaces.
On encrypt these values are passed in as strings.
But on decrypt we have bytes and this could happen.
However, this would require that then encrypting client
encoded invalid bytes.

TextDecoder could be a solution,
but is introduced in Node.js v8.3
and is "newer" then `crypto.getRandomValues`
so it would limit browser support.

Notes:
https://caniuse.com/#search=TextDecoder
https://caniuse.com/#search=getRandomValues
https://github.com/nodejs/node-v0.x-archive/issues/5650

**Comment by seebees** [comment]
Give the versions of JavaScript in the wild and how long this is going to need to be supported, I am going to close this.
