### ISSUE TITLE
KmsKeyringNode dependency on aws-sdk

### ISSUE THREAD

**Issue by RalphBragg** [aws/aws-encryption-sdk-javascript#600]
Hi,

This is a question really, are there any plans to address the requirement for the AWS Key Ring Node to have a dependency on the entire aws-sdk? It blows the package sizes significantly and i was wondering if this is likely to be addressed at all?

Kind Regards,

**Comment by medievallondoners** [comment]
+1

This is especially problematic when packaging for Lambda - when normally including the AWS-SDK in your uploaded package is not required at all.  But for my functions that use this crypto library, it is impossible to remove the SDK when preparing for Lambda because of this persistent dependency.

PLEASE FIX THIS.

**Comment by seebees** [comment]
As a workaround, you can delete the AWS SDK from the AWS Lambda zip.
I understand that this is not a great long term solution.

A tool that could remove this dependance for any AWS Lambda customer,
not only ESDK customers seems like a good feature ask for the SDK.

**Comment by RalphBragg** [comment]
This has just about mean using AWS lambda useless for our usecases. This is very poor.

**Comment by GlennyDC** [comment]
The package `aws-sdk` is no longer part of the Lambda runtime when using Node.js 18.x which means that if you want to use this library you have to include it yourself.

**Comment by RalphBragg** [comment]
So i believe this is now also causing all of the warnings about AWS v2 API being deprecated?
