### ISSUE TITLE
"Not a supported message format version" when migrating from Python 1.3.5 to JS 1.7.0 or 2.2.1

### ISSUE THREAD

**Issue by kimd14** [aws/aws-encryption-sdk-javascript#629]
I have been using version 1.3.5 of the SDK for Python for some time now, but I am interested in migrating to the SDK for JavaScript as the rest of my application back-end is in Node.

However, both versions 1.7.0 and 2.2.1 of the @aws-crypto/client-node are giving me the following error regardless of commitment policy when I attempt to decrypt my existing application data that has been encrypted with version 1.3.5 of the Python SDK:
"Not a supported message format version."

It was my understanding that 1.7.0 should be able to decrypt both message formats v1 and v2, so I'm not sure what I'm doing incorrectly here.
If it's relevant, I am using a KMSMasterKeyProvider in my existing Python implementation, but otherwise it's a very vanilla encrypt-decrypt flow.

Thank you for your time!

**Comment by lavaleri** [comment]
Hi @kimd14  

You are correct that the AWS Encryption SDK for JS should be interoperable with the AWS Encryption SDK for Python, and that version 1.7.0 should be able to decrypt both message formats v1 and v2.  

Based on your error message it looks like it’s failing at reading the first byte, which usually means that you’ve inputted something like the Base64 encoding of your encrypted message instead of the raw bytes.

Can you double check that you are attempting to decrypt the bytes of the encrypted message instead of some encoding?

If you are using a Base64 encoding and would like to just directly decrypt that, the AWS Encryption SDK for JS allows you to decrypt that directly by passing an `encoding` param. Here's an example for how to do that in one of our tests: https://github.com/aws/aws-encryption-sdk-javascript/blob/43813f463ef6c53bd4de1963e7843b56733d1bec/modules/decrypt-node/test/decrypt.test.ts#L26-L29

**Comment by kimd14** [comment]
Nailed it, it was the encoding.
Sorry about that, thanks very much for the help and the parameter tip!
