### ISSUE TITLE
Unsupported ciphertext format

### ISSUE THREAD

**Issue by gpathela** [aws/aws-encryption-sdk-javascript#823]
### Security issue notifications

If you discover a potential security issue in the AWS Encryption SDK we ask that you notify AWS Security via our [vulnerability reporting page](https://aws.amazon.com/security/vulnerability-reporting/). Please do **not** create a public GitHub issue.

### Problem:

I am trying to use this example in JS instead of Typescript. Encryption is working fine but the decryption is not working. it Is throwing an error 'Unsupported ciphertext format'

### Solution:

Can you please help me with a working Js example. 
### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by seebees** [comment]
Howdy @gpathela 

Can you share which example is failing? 

Can you describe your compute environment? Is this running on your computer or on a Lambda?

I assume you are running the Node examples, as only the decrypt-node throws `Unsupported ciphertext format`. 

Are you changing the example in anyway? The more you can tell us, the better we can re-create this issue.

For myself, to run just the node-examples, I need access to valid AWS Credentials that grant me permission to use the KMS key we test against. If you wanted to customize the example to run against a KMS key in your AWS Account, you would replace `generatorKeyId` and `keyIds` references in the `example-node` module with references to your own Keys. Otherwise, you need to attach an IAM policy that grants permission to your AWS IAM Role to invoke `Encrypt`, `Decrypt`, and `GenerateDataKey` for the KMS Keys in AWS Account 658956600833. I will paste an example policy at the end of this message.


Once I have credentials set up, I run these commands:
1. From the root of this repo, `npm ci`
2. `npm run build`
3. `cd modules/example-node`
4. `npm run test`

Even with out valid AWS Credentials, the `rsa` and `aes` examples should pass. The others will all fail with either a time out or expired token exception.

AWS IAM Policy to Invoke AWS Crypto Tools Testing KMS key:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:GenerateDataKey"
            ],
            "Resource": "arn:aws:kms:*:658956600833:key/*"
        }
    ]
}
```

**Comment by texastony** [comment]
@gpathela I am closing this issue due to in-activity.

We do not have enough information to help you.
Specifically, we do not know what example you are referring to you, 
nor do we know enough about the environment you are running this in.

If you are still encountering an issue with this, please re-open this and answer our questions.

Otherwise, if you have another issue, please open a new issue.
